name: build

on:
  push:
    branches:
      - release
      - prerelease
      - test
jobs:
  build-ubuntu:
    strategy:
      fail-fast: false
      matrix:
        tag: [plucky]
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --yes gnupg debsigs devscripts
    - name: Docker Build
      run: |
        docker build -f deployment/Dockerfile.debian -t builddeb --build-arg TAG=${{ matrix.tag }} --build-arg IMG=ubuntu deployment
        docker run -v $(pwd)/deployment/dist:/dist -v $(pwd):/jellyfin -e TAG=${{ matrix.tag }} -e IMG=ubuntu builddeb
        sudo chown --recursive $USER $(pwd)/deployment/dist
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ubuntu-${{ matrix.tag }}
        path: ${{ github.workspace }}/deployment/dist/*
